
# Document size
BAD_DOCUCMENT_SIZE_THRESHOLD = 500
OK_DOCUMENT_SIZE_THRESHOLD = 300
GOOD_DOCUMENT_SIZE_THRESHOLD = 100  # LINES
ALSO_BAD_DOCUMENT_SIZE_THRESHOLD = 20


# Function size
BAD_FUNCTION_SIZE_THRESHOLD = 40
OK_FUNCTION_SIZE_THRESHOLD = 30
GOOD_FUNCTION_SIZE_THRESHOLD = 20  # LINES

# Comments dis
GOOD_RATIO_OF_COMMENT_TO_CODE = [1, 5]
